[package]
name = "yarn-runner"
version = "0.1.0"
authors = ["Gabriel Martinez <reitaka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1"
prost = "0.6"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
prost-build = "0.6"
