use super::ast;

grammar;

pub Dialogue: ast::Dialogue = <nodes:Node+> => ast::Dialogue {
    nodes,
};

Node: ast::Node = <headers:Header+> "---" <body:Body> "===" => ast::Node {
    headers,
    body,
};

Header: ast::Header = <key:Identifier> ":" <value:Identifier> => ast::Header {
    key,
    value,
};

Body: ast::Body = <statements:Statement*> => ast::Body {
    statements,
};

Statement = {
    Identifier,
};

Identifier: String = <r"[a-zA-Z_][a-zA-Z0-9_]*"> => <>.to_string();
