#[derive(Clone, Debug)]
pub enum Token<'input> {
    Identifier(&'input str),
    HeaderValue(&'input str),
    LiteralNumber(f32),
    LiteralString(&'input str),
    KeywordTrue,
    KeywordFalse,
    KeywordNull,
    BodyStart,
    BodyEnd,
    HeaderDelimiter,
    LParen,
    RParen,
    Comma,
    CommandStart,
    CommandEnd,
    CommandIf,
    CommandElseIf,
    CommandElse,
    CommandSet,
    CommandCall,
    OptionStart,
    OptionEnd,
    OptionDelimiter,
    ExpressionStart,
    ExpressionEnd,
    FormatFunctionStart,
    FormatFunctionEnd,
    NewLine,
}
